# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_pairing.ipynb.

# %% auto 0
__all__ = ['get_test_pairs_per_category']

# %% ../nbs/03_pairing.ipynb 5
def get_test_pairs_per_category(session):
        
        valid_test_pairs = get_valid_test_pairs(session)
        

        test_categories = [
            row[0].get_category(self.filters, self.face_image_filters, self.detector, self.embeddingModel)
            for row in valid_test_pairs]

        test_pairs_per_category = defaultdict(list)
        # for face_pair, category in zip(valid_test_pairs, test_categories):
        #    test_pairs_per_category[category].append(face_pair)

        for row_enfsi_pair, category in zip(valid_test_pairs, test_categories):
            test_pairs_per_category[category].append(row_enfsi_pair)
        return test_pairs_per_category
